community/applications/bonita-super-admin-application.xml
subscription/applications/bonita-super-admin-application-sp.xml

Upgrade version of users, roles, profiles, and resources list pages.

feat (list pages): Upgrade version

---

community/applications/bonita-super-admin-application.xml
subscription/applications/bonita-super-admin-application-sp.xml

covers [RUNTIME-345](https://bonitasoft.atlassian.net/browse/RUNTIME-345)
relates to [#62](https://github.com/bonitasoft/bonita-web-pages-internal/pull/62)

fix(tenant status): Update tenant status page version to v2

---

community/applications/bonita-super-admin-application.xml
community/bonita-distrib/bonita-super-admin-application.xml
subscription/applications/bonita-super-admin-application-sp.xml
subscription/bonita-distrib/bonita-super-admin-application-sp.xml

Covers [RUNTIME-352](https://bonitasoft.atlassian.net/browse/RUNTIME-352)

fix(details pages): fix token

---

.gitignore
community/applications/bonita-super-admin-application.xml
community/bonita-distrib/bonita-super-admin-application.xml
subscription/applications/bonita-super-admin-application-sp.xml
subscription/bonita-distrib/bonita-super-admin-application-sp.xml

Relates to [RUNTIME-366](https://bonitasoft.atlassian.net/browse/RUNTIME-366)

feat: add description to the application

---

community/applications/bonita-super-admin-application.xml
community/bonita-distrib/bonita-super-admin-application.xml
subscription/applications/bonita-super-admin-application-sp.xml
subscription/bonita-distrib/bonita-super-admin-application-sp.xml

Covers [RUNTIME-366](https://bonitasoft.atlassian.net/browse/RUNTIME-366)

fix (Super admin application): Improve description

---

community/bonita-distrib/bonita-super-admin-application.xml
community/bos-distrib/applications/bonita-super-admin-application.xml
community/bos-distrib/pom.xml
community/pom.xml
subscription/bonita-distrib/bonita-super-admin-application-sp.xml
subscription/bos-distrib/applications/bonita-super-admin-application-sp.xml
subscription/bos-distrib/pom.xml
subscription/pom.xml

Community edition had been forgotten.
This commit removes duplication by extracting values in variables
Relates to [RUNTIME-366](https://bonitasoft.atlassian.net/browse/RUNTIME-366)

defect(description): fix description updated only in SP

---

community/bonita-distrib/bonita-super-admin-application.xml
community/bos-distrib/applications/bonita-super-admin-application.xml
subscription/bonita-distrib/bonita-super-admin-application-sp.xml
subscription/bos-distrib/applications/bonita-super-admin-application-sp.xml

feat(applications): Change home page to tenant status

---

infrastructure/change_version.sh

exclude bos-distrib folders when changing the release version

 fix(release): update change version script

---

community/pom.xml
subscription/pom.xml

Closes [RUNTIME-401](https://bonitasoft.atlassian.net/browse/RUNTIME-401)

defect(App): Non Editable (FINAL) app must have a different version  between community and sp

---

community/bos-distrib/applications/bonita-super-admin-application.xml
subscription/bos-distrib/applications/bonita-super-admin-application-sp.xml

covers no ticket
related to [#13](https://github.com/bonitasoft/bonita-web-pages-sp/pull/13)

feat(layout): Update tenantStatus Page

---

community/bos-distrib/applications/bonita-super-admin-application.xml
community/pom.xml
subscription/bos-distrib/applications/bonita-super-admin-application-sp.xml

Covers [RUNTIME-1301](https://bonitasoft.atlassian.net/browse/RUNTIME-1301)

Feat (Super Admin Application): Update application page version

---

community/bos-distrib/applications/bonita-super-admin-application.xml
subscription/bos-distrib/applications/bonita-super-admin-application-sp.xml

Covers [RUNTIME-1648](https://bonitasoft.atlassian.net/browse/RUNTIME-1648)
[RUNTIME-1648]: https://bonitasoft.atlassian.net/browse/RUNTIME-1648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(resource list): update version

---

community/bos-distrib/applications/bonita-super-admin-application.xml
community/pom.xml
subscription/bos-distrib/applications/bonita-super-admin-application-sp.xml
subscription/pom.xml

Covers [DEV-220](https://bonitasoft.atlassian.net/browse/DEV-220)
Depends on bonitasoft/bonita-web-pages-sp/pull/218
[DEV-220]: https://bonitasoft.atlassian.net/browse/DEV-220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(update pages versions): follow bonita-web-pages updates

---

community/bos-distrib/applications/bonita-super-admin-application.xml
subscription/bos-distrib/applications/bonita-super-admin-application-sp.xml

Covers [RUNTIME-1049](https://bonitasoft.atlassian.net/browse/RUNTIME-1049)
[RUNTIME-1049]: https://bonitasoft.atlassian.net/browse/RUNTIME-1049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore (Admin user list): Update user list page version

---

community/bos-distrib/applications/bonita-super-admin-application.xml
subscription/bos-distrib/applications/bonita-super-admin-application-sp.xml

covers [RUNTIME-1364](https://bonitasoft.atlassian.net/browse/RUNTIME-1364)
relates to [#255](https://github.com/bonitasoft/bonita-web-pages-sp/pull/255)
[RUNTIME-1364]: https://bonitasoft.atlassian.net/browse/RUNTIME-1364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(app directory): update page version

---

community/pom.xml
community/src/main/resources/bonita-distrib/bonita-super-admin-application.xml
community/src/main/resources/bos-distrib/applications/bonita-super-admin-application.xml
subscription/pom.xml
subscription/src/main/resources/bonita-distrib/bonita-super-admin-application-sp.xml
subscription/src/main/resources/bos-distrib/applications/bonita-super-admin-application-sp.xml

closes [DEV-481](https://bonitasoft.atlassian.net/browse/DEV-481)
[DEV-481]: https://bonitasoft.atlassian.net/browse/DEV-481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(maintenance): update super admin app

---

community/bos-distrib/applications/bonita-super-admin-application.xml
subscription/bos-distrib/applications/bonita-super-admin-application-sp.xml

Covers [RUNTIME-1806](https://bonitasoft.atlassian.net/browse/RUNTIME-1806)
[RUNTIME-1806]: https://bonitasoft.atlassian.net/browse/RUNTIME-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat (bonita super admin application): update application page versions

---

community/bos-distrib/applications/bonita-super-admin-application.xml
subscription/bos-distrib/applications/bonita-super-admin-application-sp.xml

Covers [RUNTIME-1806](https://bonitasoft.atlassian.net/browse/RUNTIME-1806)
[RUNTIME-1806]: https://bonitasoft.atlassian.net/browse/RUNTIME-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat (super admin application): update page versions

---

community/bos-distrib/applications/bonita-super-admin-application.xml
community/pom.xml
subscription/bos-distrib/applications/bonita-super-admin-application-sp.xml
subscription/pom.xml

Covers [RUNTIME-1825](https://bonitasoft.atlassian.net/browse/RUNTIME-1825)
[RUNTIME-1825]: https://bonitasoft.atlassian.net/browse/RUNTIME-1825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat (super admin application): update version

---

community/src/main/resources/bonita-distrib/bonita-super-admin-application.xml
community/src/main/resources/bos-distrib/applications/bonita-super-admin-application.xml
subscription/src/main/resources/bonita-distrib/bonita-super-admin-application-sp.xml
subscription/src/main/resources/bos-distrib/applications/bonita-super-admin-application-sp.xml

Related to [BPM-110](https://bonitasoft.atlassian.net/browse/BPM-110)
[BPM-110]: https://bonitasoft.atlassian.net/browse/BPM-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(xmlns): bump application-xml-schema from 1.0 to 1.1
